train_data_params = {
   'standard_train_data' : {'subdir' : 'Dataset_standard/',
               'nimages' : [3000,1500,0],
               'folders' : ['train', 'valid', 'test'],
               # image parameters
               'image_w' : 640,
               'image_h' : 640,
               'image_d' : 1,
               'label_list' : ['Spot'],
               'snr_range' : [1,25],
               'offset' : 15,
               'diameter_mean' : 12,
               'diameter_std' : 2,
               'luminosity_range' : [0.8,1],
               'density_range' : [0.01, 0.25],
               'impurity_type' : "None",
                'distance_factor' : 0.3},
                
                'big_std_train_data' : {'subdir' : 'Dataset_big_std/',
                'nimages' : [2000, 1000, 0],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : [4,25],
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 5,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.01, 0.12],
                'impurity_type' : "None",
                'distance_factor' : 0.5},

                'impurities_train_data' : {'subdir' : 'Dataset_impurities/',
                        'nimages' : [3, 0, 0],                        
                        'folders' : ['train', 'valid', 'test'],
                        # image parameters
                        'image_w' : 640,
                        'image_h' : 640,
                        'image_d' : 1,
                        'label_list' : ['Spot'],
                        'snr_range' : [4,25],
                        'offset' : 15,
                        'diameter_mean' : 12,
                        'diameter_std' : 2,
                        'luminosity_range' : [0.8,1],
                        'density_range' : [0.005,0.05],
                        'impurity_type' : "Circular and Rectangle",
                        'distance_factor' : 0.5,
                        
                        'circle_impurities': True,
                        'label_list_impurity_circle' : ['Spot_impurity'],
                        'density_range_impurity_circle' : [0.005,0.012],
                        'diameter_mean_impurity_circle' : 5,
                        'diameter_std_impurity_circle' : 3,
                        
                        'rectangle_impurities':True,
                        'label_list_impurity_rectangle' : ["Rectangle_impurity"],
                        'density_range_impurity_rectangle' : [0.005, 0.012],
                        'length_mean_impurity_rectangle' : 12,
                        'length_std_impurity_rectangle' : 5}
                        }


test_data_params = {
    '1. Standard' : {'subdir' : 'Dataset_standard/test/1_standard/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '2.1 Density 10%' : {'subdir' : 'Dataset_standard/test/2_1_density_10',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.098, 0.12],
                'impurity_type' : "None"},

                '2.2 Density 20%' : {'subdir' : 'Dataset_standard/test/2_2_density_20',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.198, 0.22],
                'impurity_type' : "None"},

                '2.3 Density 40%' : {'subdir' : 'Dataset_standard/test/2_1_density_40',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.28, 0.42],
                'impurity_type' : "None"},

                '3. Big particle std' : {'subdir' : 'Dataset_big_std/test/3_big_particle_std/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 5,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.1 SNR 20' : {'subdir' : 'Dataset_standard/test/snr_20/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 20,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.2 SNR 10' : {'subdir' : 'Dataset_standard/test/snr_10/',
                'nimages' : [0,0,1000],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.3 SNR 5' : {'subdir' : 'Dataset_standard/test/snr_5/',
                'nimages' : [0,0,1000],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.4 SNR 3' : {'subdir' : 'Dataset_standard/test/snr_3/',
                'nimages' : [0,0,1000],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 3,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.5 SNR 2' : {'subdir' : 'Dataset_standard/test/snr_2/',
                'nimages' : [0,0,1000],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 2,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '4.6 SNR 1.5' : {'subdir' : 'Dataset_standard/test/snr_1/',
                'nimages' : [0,0,1000],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 1.5,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None"},

                '5.1 Circular impurities size 4 0' : {'subdir' : 'Dataset_impurities/test/5_1_circular_impurities_size_4_0/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None",
                        'circle_impurities': True,
                        'label_list_impurity_circle' : ['Spot_impurity'],
                        'density_range_impurity_circle' : [0.008,0.012],
                        'diameter_mean_impurity_circle' : 4,
                        'diameter_std_impurity_circle' : 0,
                        },

                '5.2 Circular impurities size 6 0' : {'subdir' : 'Dataset_impurities/test/5_1_circular_impurities_size_6_0/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None",
                        'circle_impurities': True,
                        'label_list_impurity_circle' : ['Spot_impurity'],
                        'density_range_impurity_circle' : [0.008,0.012],
                        'diameter_mean_impurity_circle' : 6,
                        'diameter_std_impurity_circle' : 0,
                        },

                '5.3 Circular impurities size 8 0' : {'subdir' : 'Dataset_impurities/test/5_1_circular_impurities_size_8_0/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None",
                        'circle_impurities': True,
                        'label_list_impurity_circle' : ['Spot_impurity'],
                        'density_range_impurity_circle' : [0.008,0.012],
                        'diameter_mean_impurity_circle' : 8,
                        'diameter_std_impurity_circle' : 0,
                        },

                '5.3 Circular impurities size 9 0' : {'subdir' : 'Dataset_impurities/test/5_1_circular_impurities_size_9_0/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None",
                        'circle_impurities': True,
                        'label_list_impurity_circle' : ['Spot_impurity'],
                        'density_range_impurity_circle' : [0.008,0.012],
                        'diameter_mean_impurity_circle' : 9,
                        'diameter_std_impurity_circle' : 0,
                        },


                '6.1 Rectangle impurities size 12 5' : {'subdir' : 'Dataset_impurities/test/5_1_circular_impurities_size_12_5/',
                'nimages' : [0,0,500],
                'folders' : ['train', 'valid', 'test'],
                # image parameters
                'image_w' : 640,
                'image_h' : 640,
                'image_d' : 1,
                'label_list' : ['Spot'],
                'snr_range' : 10,
                'offset' : 15,
                'diameter_mean' : 12,
                'diameter_std' : 2,
                'luminosity_range' : [0.8,1],
                'density_range' : [0.018, 0.022],
                'impurity_type' : "None",

                        'rectangle_impurities': True,
                        'label_list_impurity_rectangle' : ["Rectangle_impurity"],
                        'density_range_impurity_rectangle' : [0.008, 0.012],
                        'length_mean_impurity_rectangle' : 12,
                        'length_std_impurity_rectangle' : 5
                        },

                '7.0 Overlap 0.3_0.5' : {'subdir' : 'Dataset_standard/test/7_0_overlap_0.3_0.5',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 0.3,
                                "max_distance_factor": 0.5},

                '7.1 Overlap 0.5_0.7' : {'subdir' : 'Dataset_standard/test/7_1_overlap_0.5_0.7',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 0.5,
                                "max_distance_factor": 0.7},

                '7.2 Overlap 0.7_0.9' : {'subdir' : 'Dataset_standard/test/7_1_overlap_0.7_0.9',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' :10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 0.5,
                                "max_distance_factor": 0.7},

                '7.3 Overlap 0.9_1.1' : {'subdir' : 'Dataset_standard/test/7_1_overlap_0.9_1.1',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 0.9,
                                "max_distance_factor": 1.1},

                '7.4 Overlap 1.1_1.3' : {'subdir' : 'Dataset_standard/test/7_1_overlap_1.1_1.3',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 1.1,
                                "max_distance_factor": 1.3},

                '7.5 Overlap 1.3_1.5' : {'subdir' : 'Dataset_standard/test/7_1_overlap_1.3_1.5',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 1.3,
                                "max_distance_factor": 1.5},

                '7.7 Overlap 1.7_1.9' : {'subdir' : 'Dataset_standard/test/7_1_overlap_1.7_1.9',
                                'nimages' : [0,0,500],
                                'folders' : ['train', 'valid', 'test'],
                                # image parameters
                                'image_w' : 640,
                                'image_h' : 640,
                                'image_d' : 1,
                                'label_list' : ['Spot'],
                                'snr_range' : 10,
                                'offset' : 15,
                                'diameter_mean' : 12,
                                'diameter_std' : 2,
                                'luminosity_range' : [0.8,1],
                                'density_range' : [0.002,0.0022],
                                'impurity_type' : "None",
                                'distance_factor' : 1.7,
                                "max_distance_factor": 1.9},

}
test_data_params = {}